/**
 * Item entry form — captures all fields for a single consignment item and adds it to the
 * current intake session. Item code is auto-generated by the backend.
 *
 * @module ItemForm
 */
import { useState, type FormEvent } from 'react'
import { addItem } from '../api/intakes'
import { fetchBrands } from '../api/items'
import { ITEM_TYPES, SIZE_OPTIONS } from '../lib/itemSizes'
import type { Item } from '../types'

const CATEGORIES = ['Skis', 'Ski Boots', 'Ski Poles', 'Snowboard', 'Snowboard Boots', 'Bindings', 'Helmet', 'Clothing', 'Other']

const emptyForm = (donateUnsold: boolean) => ({
  category: '', brand: '', type: '', description: '', color: '',
  size: '', uom: '', gender_age: '', year: '', used: false, price: '', donate_unsold: donateUnsold,
})

/**
 * Form component for adding a single item to an intake session.
 * Validates required fields (category, price), submits via the intakes API,
 * and resets after each successful submission. Item code is auto-generated by the backend.
 *
 * @param props.intakeId - ID of the intake session to which the item will be added.
 * @param props.onAdded - Callback invoked with the newly created {@link Item} on success.
 */
export function ItemForm({ intakeId, onAdded, defaultDonateUnsold = false }: {
  intakeId: number
  onAdded: (item: Item) => void
  /** Per-item donate-unsold initial state; inherits the intake's (and seller's) preference. */
  defaultDonateUnsold?: boolean
}) {
  const [f, setF] = useState(() => emptyForm(defaultDonateUnsold))
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [brandSuggestions, setBrandSuggestions] = useState<string[]>([])

  /** Brand typeahead: fetch matching existing brands as the cashier types. */
  async function handleBrandInput(value: string) {
    set('brand', value)
    if (value.trim().length < 1) { setBrandSuggestions([]); return }
    try { setBrandSuggestions(await fetchBrands(value.trim())) } catch { setBrandSuggestions([]) }
  }

  function set(k: keyof ReturnType<typeof emptyForm>, v: string | boolean) {
    setF(prev => ({ ...prev, [k]: v }))
  }

  function handleTypeChange(newType: string) {
    setF(prev => ({ ...prev, type: newType, size: '' }))
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    setError(null)
    setLoading(true)
    try {
      const item = await addItem(intakeId, {
        category: f.category || undefined,
        brand: f.brand,
        type: f.type || undefined,
        description: f.description || undefined,
        color: f.color || undefined,
        size: f.size || undefined,
        uom: f.uom || undefined,
        gender_age: f.gender_age || undefined,
        year: f.year ? parseInt(f.year) : undefined,
        used: f.used,
        price: parseFloat(f.price),
        donate_unsold: f.donate_unsold,
      })
      onAdded(item)
      setF(emptyForm(defaultDonateUnsold))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to add item')
    } finally {
      setLoading(false)
    }
  }

  const text = (id: keyof ReturnType<typeof emptyForm>, label: string, required = false) => (
    <div style={{ marginBottom: 8 }}>
      <label htmlFor={id} style={{ display: 'block', fontSize: 13, marginBottom: 2 }}>{label}</label>
      <input id={id} value={f[id] as string} onChange={e => set(id, e.target.value)} required={required} style={{ width: '100%', padding: 5, boxSizing: 'border-box' }} />
    </div>
  )

  const sizeOptions = SIZE_OPTIONS[f.type]

  return (
    <form onSubmit={handleSubmit}>
      <h4>Add Item</h4>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0 12px' }}>
        <div style={{ marginBottom: 8 }}>
          <label htmlFor="category" style={{ display: 'block', fontSize: 13, marginBottom: 2 }}>Category *</label>
          <select id="category" value={f.category} onChange={e => set('category', e.target.value)} required style={{ width: '100%', padding: 5 }}>
            <option value="">— select —</option>
            {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
        <div style={{ marginBottom: 8 }}>
          <label htmlFor="brand" style={{ display: 'block', fontSize: 13, marginBottom: 2 }}>Brand *</label>
          <input
            id="brand"
            list="brand-suggestions"
            value={f.brand}
            onChange={e => handleBrandInput(e.target.value)}
            required
            style={{ width: '100%', padding: 5 }}
          />
          <datalist id="brand-suggestions">
            {brandSuggestions.map(b => <option key={b} value={b} />)}
          </datalist>
        </div>
        <div style={{ marginBottom: 8 }}>
          <label htmlFor="type" style={{ display: 'block', fontSize: 13, marginBottom: 2 }}>Type</label>
          <select id="type" value={f.type} onChange={e => handleTypeChange(e.target.value)} style={{ width: '100%', padding: 5 }}>
            <option value="">— select type —</option>
            {ITEM_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
          </select>
        </div>
        <div style={{ marginBottom: 8 }}>
          <label htmlFor="description" style={{ display: 'block', fontSize: 13, marginBottom: 2 }}>Description</label>
          <input
            id="description"
            value={f.description}
            onChange={e => set('description', e.target.value)}
            maxLength={99}
            style={{ width: '100%', padding: 5, boxSizing: 'border-box' }}
          />
          <div style={{ textAlign: 'right', fontSize: 11, color: f.description.length >= 90 ? '#ef4444' : '#94a3b8', marginTop: 2 }}>
            {f.description.length} / 99
          </div>
        </div>
        {text('color', 'Color')}
        <div style={{ marginBottom: 8 }}>
          <label htmlFor="size" style={{ display: 'block', fontSize: 13, marginBottom: 2 }}>Size</label>
          {sizeOptions ? (
            <select id="size" value={f.size} onChange={e => set('size', e.target.value)} style={{ width: '100%', padding: 5 }}>
              <option value="">— select size —</option>
              {sizeOptions.map(s => <option key={s} value={s}>{s}</option>)}
            </select>
          ) : (
            <input id="size" value={f.size} onChange={e => set('size', e.target.value)} style={{ width: '100%', padding: 5, boxSizing: 'border-box' }} />
          )}
        </div>
        <div style={{ marginBottom: 8 }}>
          <label htmlFor="gender_age" style={{ display: 'block', fontSize: 13, marginBottom: 2 }}>Gender/Age</label>
          <select id="gender_age" value={f.gender_age} onChange={e => set('gender_age', e.target.value)} style={{ width: '100%', padding: 5 }}>
            <option value="">— select —</option>
            {['Adult', 'Youth', 'Toddler', 'Unisex'].map(g => <option key={g} value={g}>{g}</option>)}
          </select>
        </div>
        {text('year', 'Year')}
        <div style={{ marginBottom: 8 }}>
          <label htmlFor="price" style={{ display: 'block', fontSize: 13, marginBottom: 2 }}>Price *</label>
          <input id="price" type="number" min="0" step="0.01" value={f.price} onChange={e => set('price', e.target.value)} required style={{ width: '100%', padding: 5, boxSizing: 'border-box' }} />
        </div>
      </div>
      <div style={{ marginBottom: 10, display: 'flex', gap: 16 }}>
        <label>
          <input type="checkbox" checked={f.used} onChange={e => set('used', e.target.checked)} />
          {' '}Used item
        </label>
        <label>
          <input type="checkbox" checked={f.donate_unsold} onChange={e => set('donate_unsold', e.target.checked)} />
          {' '}Donate if unsold (override intake preference)
        </label>
      </div>
      {error && <div role="alert" style={{ color: 'red', marginBottom: 8 }}>{error}</div>}
      <button type="submit" disabled={loading}>Add Item</button>
    </form>
  )
}
