"""add unique constraints on user(event_id,username) and seller(event_id,code)

Revision ID: 77bbabfd3124
Revises: cb5e7741945c
Create Date: 2026-04-03 12:36:16.814920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77bbabfd3124'
down_revision: Union[str, None] = 'cb5e7741945c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller') as batch_op:
        batch_op.create_unique_constraint('uq_seller_event_code', ['event_id', 'code'])
    with op.batch_alter_table('user') as batch_op:
        batch_op.create_unique_constraint('uq_user_event_username', ['event_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint('uq_user_event_username', type_='unique')
    with op.batch_alter_table('seller') as batch_op:
        batch_op.drop_constraint('uq_seller_event_code', type_='unique')
    # ### end Alembic commands ###
