"""add vendor commission rate to event

Revision ID: c33c29d690e7
Revises: 71f8527c351c
Create Date: 2026-04-11 22:06:29.384593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33c29d690e7'
down_revision: Union[str, None] = '71f8527c351c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_commission_rate', sa.Float(), nullable=False, server_default='0.30'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('vendor_commission_rate')

    # ### end Alembic commands ###
